language: node_js
node_js:
- node
- '6'
after_success: npm run publishTestResults
deploy:
  provider: npm
  email: krebs.bruno@gmail.com
  on:
    tags: true
    repo: brunokrebs/rest-flex
env:
  matrix:
  - secure: VsVhTIVi6vOi3t/FtOFpmtu5oWG1LLw8qOArc3Ya0bxHXwDKfcWEjD0q/Ks/I3fOZeSYzGPCwsykIpx8tmmL91H2TSAbfIalqCZUDVLJqsFbaBuVZ/b3CPcyg7g/9HbPG8JzSxFZI06OkTYiPWTX2R79TzzBfhJzYnHAukuW8SxXQZ224w7RXbM/N5DWLNilJket+r6JEJhsDvXaOawR8MHGCGVUG8uGiPOjzEFKUFH+2TrKNzlfAJahHRHD9U5Ac6zj5Mz4iBDmjSe8lJHXJUrN58hld/Qh7NiSk4LdjkIdO5hO0v6Klvf8Dedu1CuSziHXdgx1hdZKaYN0kzSrrMZsA4Qt57p2EZL65GIH6D1Oi1Tg1Sv+m2W7GgKhTTrTyXR3eCK2Rp9LlsHStxpdx8EN1AaIOkFf4fbQJhgrb2nv3mfKMVEnEFKfYPlFtzupJLJSj4KGA1mKoW/6BOjjwmFIjMZCL4xEK0jOTvEfB7zazKh4pODKFVvOuiQRthof91xCJmDP0RYMmpZU0gr2SYHY5Y3mxSwDJxB1d3jke3n9uBkaqoNxYw+kQVCNm97eOtfBn2Q1VJ+UE2j/rf2PTpFjWyl0pQBRpexm/VZ0dY1CR+KV3Ze2EnhC2g/LMXB9TQ5+tmnaR6dsAfzUPNcjF+mRrpFLqbKGRC/9G1J9nAk=
